### ISSUE TITLE
Minor inconsistency with environment name in python-installation.asc

### ISSUE THREAD

**Issue by rodti** [LSDtopotools/LSDTT_documentation#4]
In the following section the environment name is referred to as 'LSDMT':

```
If you are using LSDMT_version_0.2.2.txt:

$ conda create --name LSDMT --file LSDMT_version_0.2.1.txt
```

However the rest of the how-to uses environment name 'LSDTT'.

**Comment by simon-m-mudd** [comment]
Fixed this typo. Thanks for highlighting it.
